[project]
name = "iva"
version = "0.2.0"
description = "intelligent virtual assistant"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "bleak>=2.1.1",
    "ddgs>=9.10.0",
    "dotenv>=0.9.9",
    "duckduckgo-search>=8.1.1",
    "gtts>=2.5.4",
    "ipykernel>=7.1.0",
    "mutagen>=1.47.0",
    "numpy>=2.3.5",
    "pydub>=0.25.1",
    "python-dotenv>=1.2.1",
    "python-vlc>=3.0.21203",
    "pyvlc>=1.0.1",
    "pywin32>=311",
    "pywizlight>=0.6.3",
    "readability-lxml>=0.8.4.1",
    "realtimestt>=0.3.104",
    "requests>=2.32.5",
    "schedule>=1.2.2",
    "scrapy>=2.14.1",
    "selenium>=4.39.0",
    "sounddevice>=0.5.3",
    "torch>=2.9.1",
    "vosk>=0.3.45",
]

